import React from 'react';
import { TrendingUp, AlertTriangle, Info } from 'lucide-react';

const PredictionResults = ({ predictions, selectedSymptoms }) => {
  const getConfidenceColor = (probability) => {
    if (probability >= 0.7) return 'bg-red-500';
    if (probability >= 0.4) return 'bg-yellow-500';
    return 'bg-green-500';
  };

  const getConfidenceText = (probability) => {
    if (probability >= 0.7) return 'High Confidence';
    if (probability >= 0.4) return 'Medium Confidence';
    return 'Low Confidence';
  };

  const getConfidenceTextColor = (probability) => {
    if (probability >= 0.7) return 'text-red-700';
    if (probability >= 0.4) return 'text-yellow-700';
    return 'text-green-700';
  };

  return (
    <div className="bg-white rounded-2xl card-shadow p-8">
      <div className="flex items-center space-x-3 mb-6">
        <TrendingUp className="w-8 h-8 text-green-600" />
        <h2 className="text-2xl font-bold text-gray-800">Prediction Results</h2>
      </div>

      {/* Selected Symptoms Summary */}
      <div className="bg-blue-50 rounded-lg p-4 mb-6">
        <h3 className="font-semibold text-blue-800 mb-2">Selected Symptoms:</h3>
        <div className="flex flex-wrap gap-2">
          {selectedSymptoms.map((symptom, index) => (
            <span
              key={index}
              className="bg-blue-200 text-blue-800 px-3 py-1 rounded-full text-sm font-medium"
            >
              {symptom}
            </span>
          ))}
        </div>
      </div>

      {/* Predictions */}
      <div className="space-y-4">
        {predictions.map((prediction, index) => (
          <div
            key={index}
            className="prediction-card border border-gray-200 rounded-xl p-6 hover:border-blue-300"
          >
            <div className="flex items-center justify-between mb-4">
              <div className="flex items-center space-x-3">
                <div className="flex items-center justify-center w-8 h-8 bg-blue-100 text-blue-600 rounded-full font-bold">
                  {index + 1}
                </div>
                <h3 className="text-xl font-semibold text-gray-800">
                  {prediction.disease}
                </h3>
              </div>
              <div className="text-right">
                <div className="text-2xl font-bold text-gray-800">
                  {(prediction.probability * 100).toFixed(1)}%
                </div>
                <div className={`text-sm font-medium ${getConfidenceTextColor(prediction.probability)}`}>
                  {getConfidenceText(prediction.probability)}
                </div>
              </div>
            </div>

            {/* Probability Bar */}
            <div className="w-full bg-gray-200 rounded-full h-3 mb-4">
              <div
                className={`h-3 rounded-full transition-all duration-500 ${getConfidenceColor(prediction.probability)}`}
                style={{ width: `${prediction.probability * 100}%` }}
              ></div>
            </div>

            {/* Additional Info */}
            <div className="flex items-start space-x-2 text-sm text-gray-600">
              <Info className="w-4 h-4 mt-0.5 flex-shrink-0" />
              <span>
                This prediction is based on the symptoms you selected. The confidence level indicates 
                how closely your symptoms match typical cases of this condition.
              </span>
            </div>
          </div>
        ))}
      </div>

      {/* Disclaimer */}
      <div className="mt-8 bg-amber-50 border border-amber-200 rounded-lg p-4">
        <div className="flex items-start space-x-3">
          <AlertTriangle className="w-6 h-6 text-amber-600 flex-shrink-0 mt-0.5" />
          <div>
            <h4 className="font-semibold text-amber-800 mb-1">Medical Disclaimer</h4>
            <p className="text-amber-700 text-sm">
              These predictions are generated by an AI model and are for informational purposes only. 
              They should not be used as a substitute for professional medical diagnosis. Please consult 
              with a qualified healthcare provider for proper medical evaluation and treatment.
            </p>
          </div>
        </div>
      </div>
    </div>
  );
};

export default PredictionResults;